### ISSUE TITLE
Blog links dead

### ISSUE THREAD

**Issue by altineller** [sfwa/TRICAL#10]
First of all thank you very much for the hardwork.

Some of the documentation here points to http://au.tono.my/ which does not exist anymore.

Is there anyway we can reach the:
http://au.tono.my/log/20131213-trical-magnetometer-calibration.html
and
http://au.tono.my/log/trical-visualisation.html

Best regards,
Can

**Comment by bendyer** [comment]
Hi Can,

Sorry about that! It's been a while since we've worked on this. Here's an archive of that site, minus some of the videos and larger images. You should be able to unzip and open the relevant pages with full functionality locally.
[diary.zip](https://github.com/user-attachments/files/17514388/diary.zip)

Regards,
Ben
